### ISSUE TITLE
The morphological analysis results of bareunpy and Rbareun are different.

### ISSUE THREAD

**Issue by sdkparkforbi** [bareun-nlp/bareunpy#5]
"평가가 차가워지고 있다" 
bareunpy: "평가"+"가"+"차가워지"+"고"+"있"+"다"
RBareun: "평가"+"가"+"차갑"+"어"+"지"+"고"+"있"+"다"

 "15일과 16일 양일간"
 bareunpy: "양"+"일간"
 RBareun: "양"+"일"+"간" 
 
 "어린잎채소"
 bareunpy: "어린"+"잎채소", 
 RBareun: "어리"+"ㄴ"+"잎"+"채소" 
 
 "창업 8년차인 젠큐릭스"
  bareunpy: "8"+"년"+"차인"+"젠큐릭스",
  RBareun: "8"+"년"+"차"+"이"+"ㄴ"+"젠큐릭스"
 
 RBareun is showing better results than bareunpy.  What could be the reasons for this to happen?

**Comment by YugwonWon** [comment]
@sdkparkforbi 

In bareunpy, you can select the options "auto_jointing" and "auto_spacing". They are set to True by default. If you don't enable this feature, the result will be the same as RBareun, but RBareun is still only available by default. This will be patched to be selectable in the future.

Example of turning off the feature in bareunpy.
response = my_tagger.tags([text], auto_jointing=False, auto_spacing=False)

Bareun performs morphological split, then performs the spacing function, and after applying the spacing, it gives the appropriate tagging to the stem. It post-processes the tagging results by consulting several built-in dictionaries, as this can be useful for some people. If syntactic morphology results are important to you, you may want to turn that option off.

For example, 차인("cha-in (someone who enjoys drinking tea.)") and 잎채소("leafy vegetable") and 차가워지다(cool) are listed as dictionaries in the 우리말샘(Korean Woorimalsam dictionary). (https://opendict.korean.go.kr/search/searchResult?focus_name_top=query&query=%EC%B0%A8%EC%9D%B8)

**Comment by hunbl** [comment]
We also set the default values of auto_spacing, auto_jointing to TRUE in RBareun. Each value can now be referenced and specified as tagged$auto_spacing, tagged$auto_jointing.

**Comment by gih2yun** [comment]
@sdkparkforbi 

According to your report, without auto_spacing and auto_jointing returns more reasonable results.

I've found some logical errors on handling auto_jointing option, it will be fixed at release v2.2.0.

Thanks.
